---
title: "The Bachelor"
output: html_document
date: "2024-03-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(tidyverse)
library(janitor)
library(here)
```

```{r}
season_details <- read.csv("season_details.csv")%>% clean_names()
```

```{r}
glimpse(season_details)
```

```{r}
head(season_details)
```

```{r}
still_together<- season_details%>%
  group_by(season, full_name, still_together)%>%
  filter(still_together=="TRUE")
```

```{r}
count(still_together, season)
```
Make a plot to show the number of couples still together by season. 
```{r}
ggplot(still_together, aes(x=season, y=full_name))+
  geom_col(fill = "darkred", alpha=0.8)+
  coord_flip()+
  labs(title="Number of Couples Still Together by Season", x="Season", y="Number of Couples")+
  theme(axis.text.x = element_text(angle = 60, hjust = 1),
        plot.title = element_text(size = 14, face="bold"))+
  geom_text(aes(label = season), vjust = -0.2, size = 3, color = "black")
```
```{r}
colours()
```

Make a plot that shows all of the couples.
```{r}
ggplot(season_details, aes(x=season, y=full_name, fill=still_together))+
  geom_col()+
  coord_flip()+
  labs(title="Couple's Relationship Status by Season", x="Season", y="Name of Couples")+
  theme(axis.text.x=element_text(angle=90, hjust = 1))
```








```{r}
hometowns <- read.csv("hometown_coordinates.csv")%>% clean_names()
```















```{r}
eliminations <- read.csv("eliminations_and_dates.csv")%>% clean_names()
```














```{r}
contestants <- read.csv("contestant_details.csv")%>% clean_names()
```



How many contestants are in each season?
```{r}
count(contestants, season)

```
Make a plot that shows the number of contestants in each season.
```{r}
ggplot(contestants, aes(x=season))+
  geom_bar(fill = "darkred", alpha=0.8)+
  labs(title="Number of Contestants by Season", x="Season", y="Number of Contestants")+
  theme(axis.text.x = element_text(angle = 60, hjust = 1),
        plot.title = element_text(size = 14, face="bold"))+
  geom_text(stat = "count", aes(label = ..count..), vjust = -0.2, size = 3, color = "black")

```












```{r}
compact_eliminations <- read.csv("eliminations_and_dates_compact.csv") %>% clean_names()
```













